routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QNAController@show')->name ('get.index');

Auth::routes();

Route::resource('qna', 'QNAController')->middleware('auth');
Route::get('/search', 'QNAController@search')->middleware('auth')->name('search.data'); //this is for search on admin dashboard
Route::get('/admin', 'AuthController@getLogin')->middleware('guest')->name('get.login');
Route::post('/login', 'AuthController@postLogin')->middleware('guest')->name('post.login');
Route::get('/logout', 'AuthController@logout')->middleware('auth')->name('logout');
Route::get('/upload', 'QNAController@uploadfile')->middleware('auth')->name('upload');
Route::get('/showDataInfo/{jenis}', 'QNAController@process')->middleware('auth')->name('get.dataInfo');
Route::get('/searchData', 'QNAController@searchForLandingPage')->middleware('guest')->name('search.data.info'); //this is for search on landing page

Route::get('/imageUpload', 'UploadImageController@index')->name('get.imageUpload');
Route::post('/imageUpload', 'UploadImageController@upload')->name('post.imageUpload');
Route::delete('/imageUpload/{id}', 'UploadImageController@destroy')->name('delete.imageUpload');

app/Lainlain.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lainlain extends Model
{
    protected $table = 'lainlain';
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'images', 'keteranagan',
    ];
}

app/Qna.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Qna extends Model
{
    protected $table = 'qna';
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'jenis', 'pertanyaan', 'jawaban',
    ];
}

app/UploadImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UploadImage extends Model
{
    protected $table = 'upload_images';

    protected $fillable = [
        'title', 'image'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Illuminate\Http\Request;

class AuthController extends Controller
{
    public function getLogin () {
        return view ('login');
    }

    public function getLogout () {
        return view ('index');
    }

    public function postLogin (Request $request) {
        if(\Auth::attempt(['name' => $request->name, 'password' => $request->password])){
            return redirect()->route('qna.index');
        }else{
            return view('login')->with('success', 'Gagal Login');
        }
    }

    public function logout (Request $request) {
        \Auth::logout();

        return redirect()->route('get.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/QNAController.php
<?php

namespace App\Http\Controllers;

use App\Qna;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class QNAController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $qna = Qna::all();
        return view('admin/showDataInfo', compact('qna'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.createData');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validasi = $request->validate([
            'jenis' => 'required',
            'pertanyaan' => 'required',
            'jawaban' => 'required',
        ]);
        $qna = Qna::create($validasi);

        return redirect()->route('qna.create')->with('successCreateData', 'Data berhasil ditambah !')->with(compact('validasi'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Qna  $qna
     * @return \Illuminate\Http\Response
     */
    public function show(Qna $qna)
    {
        return view ('showDataInfo');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Qna  $qna
     * @return \Illuminate\Http\Response
     */
    public function edit(Qna $qna)
    {
        return view('admin.edit', compact('qna'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Qna  $qna
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validasi = $request->validate([
            'jenis' => 'required',
            'pertanyaan' => 'required',
            'jawaban' => 'required'
        ]);
        Qna::whereId($id)->update($validasi);

        return redirect()->route('qna.index')->with('successUpdate', 'Data berhasil di update !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Qna  $qna
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $qna = Qna::findOrFail($id);
        $qna->delete();

        return redirect()->back()->with('successDelete', 'Data berhasil dihapus !');
    }

    public function uploadfile() {
        return view('admin.upload');
    }

    public function process ($jenis) {
        return view('admin/showDataInfo', compact('jenis'));
    }

    public function search (Request $request)
    {
        $input = $request->search;
        $search = DB::table('qna')->where('pertanyaan', 'like', "%" .$input. "%")->get();
        return view('admin.searchData', compact('search'));
    }

    public function searchForLandingPage (Request $request)
    {
        $input = $request->search;
        $search = DB::table('qna')->where('pertanyaan', 'like', "%" .$input. "%")->orWhere('jawaban', 'like', "%" .$input. "%")->get();
        return view('searchDataInfo', compact('search'));
    }
}

app/Http/Controllers/UploadImageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\UploadImage;
use Illuminate\Support\Facades\Storage;
use File;

class UploadImageController extends Controller
{
    public function index () {
        $images = UploadImage::get();
        return view('admin.imageUpload', compact('images'));
    }

    public function upload (Request $request) {
        $this->validate($request, [
            'title' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        $input['image'] = time().'.'.$request->image->getClientOriginalExtension();

        $request->image->move(public_path('images'), $input['image']);


        $input['title'] = $request->title;

        UploadImage::create($input);


    	return back()->with('success','Image Uploaded successfully.');
    }

    public function destroy ($id) {
        UploadImage::find($id)->delete();

      return back()->with('success','Image removed successfully with id : .');
    }
}

resources/views/admin/createData.blade.php
@extends('admin.index')

<?php
    $qna = DB::table('qna')->select('id', 'jenis', 'pertanyaan', 'jawaban')->get();
?>

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        </div><br/>
    @endif
    @if(session()->get('successCreateData'))
        <div class="alert alert-success">
        {{ session()->get('successCreateData') }}
        </div><br/>
    @endif

    <div class="card uper">
    <div class="card-body">
        <form method="post" action="{{ route('qna.store') }}">
            @csrf
            <div class="form-group">
                <label>Jenis</label>
                <div class="form-group">
                    <select name="jenis">
                    <option value="Pasang Baru">Pasang Baru</option>
                    <option value="Perubahan Daya">Perubahan Daya</option>
                    <option value="Balik Nama">Balik Nama</option>
                    <option value="Pesta">Pesta</option>
                    <option value="SLO">SLO</option>
                    <option value="IML">IML</option>
                    <option value="Geser">Geser Meter/Geser Tiang/Geser Sr</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label>Pertanyaan</label>
                <textarea class="form-control" name="pertanyaan"></textarea>
            </div>
            <div class="form-group">
                <label>Jawaban</label>
                <textarea style="height:300px;" class="form-control" name="jawaban"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Tambah Data</button>
        </form>
    </div>
    </div>

    <br><br>

    @if(session()->get('successUpdate'))
        <div class="alert alert-success">
    {{ session()->get('successUpdate') }}
        </div><br/>
    @endif
    @if(session()->get('successDelete'))
        <div class="alert alert-success">
        {{ session()->get('successDelete') }}
        </div><br/>
    @endif


    <br><br>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.index')

@section('judul')
    <p>Edit Data</p>
@endsection

@section('content')
<div class="card uper">
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br/>
    @endif

    <form action="{{ route('qna.update',$qna->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label>Jenis</label>
            <div class="form-group">
                @if ($qna->jenis == 'Pasang Baru')
                    <select name="jenis">
                        <option value="Pasang Baru" selected>Pasang Baru</option>
                        <option value="Perubahan Daya">Perubahan Daya</option>
                        <option value="Balik Nama">Balik Nama</option>
                        <option value="Pesta">Pesta</option>
                        <option value="SLO">SLO</option>
                        <option value="IML">IML</option>
                        <option value="Geser">Geser Meter/Geser Tiang/Geser SR</option>
                    </select>
                @elseif ($qna->jenis == 'Perubahan Daya')
                    <select name="jenis">
                        <option value="Pasang Baru">Pasang Baru</option>
                        <option value="Perubahan Daya" selected>Perubahan Daya</option>
                        <option value="Balik Nama">Balik Nama</option>
                        <option value="Pesta">Pesta</option>
                        <option value="SLO">SLO</option>
                        <option value="IML">IML</option>
                        <option value="Geser">Geser Meter/Geser Tiang/Geser SR</option>
                    </select>
                @elseif ($qna->jenis == 'Balik Nama')
                <select name="jenis">
                    <option value="Pasang Baru">Pasang Baru</option>
                    <option value="Perubahan Daya">Perubahan Daya</option>
                    <option value="Balik Nama" selected>Balik Nama</option>
                    <option value="Pesta">Pesta</option>
                    <option value="SLO">SLO</option>
                    <option value="IML">IML</option>
                    <option value="Geser">Geser Meter/Geser Tiang/Geser SR</option>
                </select>
                @elseif ($qna->jenis == 'Pesta')
                    <select name="jenis">
                        <option value="Pasang Baru">Pasang Baru</option>
                        <option value="Perubahan Daya">Perubahan Daya</option>
                        <option value="Balik Nama">Balik Nama</option>
                        <option value="Pesta" selected>Pesta</option>
                        <option value="SLO">SLO</option>
                        <option value="IML">IML</option>
                        <option value="Geser">Geser Meter/Geser Tiang/Geser SR</option>
                    </select>
                @elseif ($qna->jenis == 'SLO')
                    <select name="jenis">
                        <option value="Pasang Baru">Pasang Baru</option>
                        <option value="Perubahan Daya">Perubahan Daya</option>
                        <option value="Balik Nama">Balik Nama</option>
                        <option value="Pesta">Pesta</option>
                        <option value="SLO" selected>SLO</option>
                        <option value="IML">IML</option>
                        <option value="Geser">Geser Meter/Geser Tiang/Geser SR</option>
                    </select>
                @elseif ($qna->jenis == 'IML')
                    <select name="jenis">
                        <option value="Pasang Baru">Pasang Baru</option>
                        <option value="Perubahan Daya">Perubahan Daya</option>
                        <option value="Balik Nama">Balik Nama</option>
                        <option value="Pesta">Pesta</option>
                        <option value="SLO">SLO</option>
                        <option value="IML" selected>IML</option>
                        <option value="Geser">Geser Meter/Geser Tiang/Geser SR</option>
                    </select>
                @else
                    <select name="jenis">
                        <option value="Pasang Baru">Pasang Baru</option>
                        <option value="Perubahan Daya">Perubahan Daya</option>
                        <option value="Balik Nama">Balik Nama</option>
                        <option value="Pesta">Pesta</option>
                        <option value="SLO">SLO</option>
                        <option value="IML">IML</option>
                        <option value="Geser" selected>Geser Meter/Geser Tiang/Geser SR</option>
                    </select>
                @endif
            </div>
        </div>
        <div class="form-group">
            <label>Pertanyaan</label>
            <textarea class="form-control" name="pertanyaan">{{ $qna->pertanyaan }}</textarea>
        </div>
        <div class="form-group">
            <label>Jawaban</label>
            <textarea style="height:300px;" class="form-control" name="jawaban">{{ $qna->jawaban }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">Edit Data</button>
        </div>

    </form>
  </div>
</div>
@endsection

resources/views/admin/imageUpload.blade.php
@extends('admin.index')

@section('content')
<meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <!-- References: https://github.com/fancyapps/fancyBox -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>

    <!-- call image_upload.css for showing image -->
    <link rel="stylesheet" href="css/image_upload.css">

    <style type="text/css">
        .gallery
        {
            display: inline-block;
            margin-top: 20px;
        }
        .close-icon{
            border-radius: 50%;
            position: absolute;
            right: 5px;
            top: -10px;
            padding: 5px 8px;
        }
        .form-image-upload{
            background: #e8e8e8 none repeat scroll 0 0;
            padding: 15px;
        }
    </style>
</head>

<body>
<div class="container">
    <form action="{{ route('post.imageUpload') }}" class="form-image-upload" method="POST" enctype="multipart/form-data">
        {!! csrf_field() !!}
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                </div>
            @endif

        <!-- <div class="column"> -->
            <div class="col-md-2">
                <strong>Jenis:</strong>
                <select name="title">
                    <option value="Brosur Daftar Instalir Resmi">Brosur Daftar Instalir Resmi</option>
                    <option value="Brosur PLN">Brosur PLN</option>
                    <option value="Jasa SLO">Jasa SLO</option>
                    <!-- <option value="Brosur 4">Brosur 4</option>
                    <option value="Brosur 5">Brosur 5</option>
                    <option value="SLO">SLO</option>
                    <option value="IML">IML</option> -->
                </select>
            </div>
                <br><br><br>
            <div class="col-md-5">
                <strong>Image:</strong>
                <input type="file" name="image" class="form-control">
            </div>
            <div class="col-md-2">
                <br/>
                <button type="submit" class="btn btn-success">Upload</button>
            </div>
        <!-- </div> -->
    </form>
        <br>
        <div class="row">
          @if($images->count())
              @foreach($images as $image)
                <div class="column">
                  <div class="card">
                    <div class="container">
                      <a class="thumbnail fancybox" rel="ligthbox" href="/images/{{ $image->image }}">
                          <img class="img-responsive" alt="{{ $image->title }}" style="width:200px; height:300px;" src="/images/{{ $image->image }}" >
                      </a>
                    </div>
                    <p style="padding-top: 10px">{{ $image->title }}</p>
                    <div class="container">
                      <form action="{{ route('delete.imageUpload',$image->id) }}" method="POST">
                        <input type="hidden" name="_method" value="delete">
                        {!! csrf_field() !!}
                          <button type="submit" class="btn btn-danger center">Hapus</button>
                      </form>
                    </div>
                  </div>
                </div>
              @endforeach
          @endif
</div> <!-- container / end -->
</body>

<script type="text/javascript">
    $(document).ready(function(){
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });
    });
</script>
@endsection

resources/views/admin/index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Dashboard Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.4/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">PLN ULP KRIAN</a>
  <form action="{{ route('search.data') }}" method="GET">
    <input style="background: white" class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search" name="search">
  </form>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="btn btn-danger btn-danger" href="{{ route('logout') }}">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('qna.create') }}">
                    <span data-feather="users"></span>
                    Tambah Data<span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('qna.index') }}">
                    <span data-feather="users"></span>
                    Sunting Data<span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('get.imageUpload') }}">
                    <span data-feather="file-text"></span>
                    Upload Brosur
                </a>
            </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>

      <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->

      <!-- show data -->
      @yield('content')
      <!-- end show data -->
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.4/examples/dashboard/dashboard.js"></script></body>
</html>

resources/views/admin/searchData.blade.php
@extends('admin.index', ['search' => $search])

@section('content')
<style media="screen">
  pre{
    font-family:calibri,arial,sans-serif;
    background-color: inherit; overflow-wrap: break-word;font-size: 16px; ; color: #000000;
    white-space: pre-wrap;
  }
</style>
    <table class="table table-striped border text-center">
        <thead>
            <tr>
                <td>Jenis</td>
                <td>Pertanyaan</td>
                <td>Jawaban</td>
                <td colspan="2">Kelola Data</td>
            </tr>
        </thead>
        <tbody>
            @foreach($search as $see)
                <tr>
                    <td>{{$see->jenis}}</td>
                    <td style="text-align:left;">{{$see->pertanyaan}}</td>
                    <td style="text-align:left; width:60%;"><pre>{{ $see->jawaban }}</pre></p></td>
                    <td><a href="{{ route('qna.edit', $see->id) }}" class="btn btn-warning">Edit</a></td>
                    <td>
                        <form action="{{ route('qna.destroy', $see->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/admin/showDataInfo.blade.php
<?php
    $value = DB::table('qna')->select('id','jenis', 'pertanyaan', 'jawaban')->where('jenis', $jenis ?? '')->get();
    $kind = ["Pasang Baru", "Perubahan Daya", "Balik Nama", "Pesta", "SLO", "IML","Geser"];
?>

@extends('admin.index')

@section('content')
<style media="screen">
  pre{
    font-family:calibri,arial,sans-serif;
    background-color: inherit; overflow-wrap: break-word;font-size: 16px; ; color: #000000;
    white-space: pre-wrap;
  }
</style>
    @foreach($kind as $k)
        <a href="{{ route('get.dataInfo',$k) }}" class="btn btn-info">{{ $k }}</a>&nbsp&nbsp
    @endforeach
    <br><br>
    <table class="table table-striped border text-center">
        <thead>
            <tr>
                <td>Jenis</td>
                <td>Pertanyaan</td>
                <td>Jawaban</td>
                <td colspan="2">Kelola Data</td>
            </tr>
        </thead>
        <tbody>
            @foreach($value as $qnashow)
                <tr>
                    <td>{{$qnashow->jenis}}</td>
                    <td style="text-align:left;">{{$qnashow->pertanyaan}}</td>
                    <td style="text-align:left; width:60%;"><pre>{{ $qnashow->jawaban }}</pre></p></td>
                    <td><a href="{{ route('qna.edit', $qnashow->id) }}" class="btn btn-warning">Edit</a></td>
                    <td>
                        <form action="{{ route('qna.destroy', $qnashow->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/searchDataInfo.blade.php
<?php
    $no = 1;
    $collapse = ["collapseOne", "collapseTwo", "collapseThree", "collapseFour", "collapseFive", "collapseSix"];
?>

@extends('index', ['search' => $search])

@section('content')
<style media="screen">
  pre{
    font-family:calibri,arial,sans-serif;
    background-color: inherit; overflow-wrap: break-word;font-size: 16px; ; color: #000000;

  }
</style>

<div class="section">
    <div class="container">
       <div class="row">
          <div class="col-xs-12">
             <div class="container">
                <div class="row">
                   <div class="col-md-12">
                      <h3 style="text-align: center; color:black;">Hasil Dari Yang Anda Masukkan ...</h3>
                      <div class="section-title-divider"></div>
                      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                         <div class="panel panel-default">
                            @foreach ($search as $see)
                                <div>
                                    <div class="panel-body">
                                    <div class="accordion">
                                            <div class="accordion-item">
                                                <a style="color: black;"><b>{{ $see->pertanyaan }}</b> ({{ $see->jenis }})</a>
                                                <div class="content">
                                                <pre>{{ $see->jawaban }}</pre>
                                                </div>
                                            </div>
                                    </div>
                                    </div>
                                </div>
                            @endforeach
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>
@endsection